export const SERVICE_CATEGORIES = [
  "Plumbing",
  "Electrical",
  "Hvac",
  "Carpentry",
  "Cleaning",
  "Gardening",
  "Pest control",
  "Painting",
  "Roofing",
  "Masonry",
  "Welding",
  "Landscaping",
  "Flooring",
  "Remodeling",
  "Construction",
  "Handyman",
  "Appliance repair",
  "Moving",
  "Security",
  "Locksmith",
  "Car wash",
  "Car detailing",
  "Carpentry",
  "Home improvement",
  "Home repair",
  "Home cleaning",
  "Home maintenance",
  "Home organization",
  "Other",
];
